spring:
  datasource:
    url:
    driver-class-name:
  mvc:
    view:
      prefix: /WEB-INF/views/   # Controller가 리턴시 앞에붙는 경로 명
      suffix: .jsp              # Controller가 리턴시 뒤에붙는 경로 명
  devtools:
    livereload:
      enabled: true
server:
  forward-headers-strategy: framework
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    
logging:
  level:
    root: info
  config: classpath:log4j2.yml
